### ISSUE TITLE
`Failed to extract project data from GitHub due to an invalid access token` when creating burndown chart for GitHub enterprise organization

### ISSUE THREAD

**Issue by naomimow** [thehale/github-projects-burndown-chart#28]
Hello,

I would like to create a burndown chart for a GitHub enterprise organization. I have followed all the steps to clone and setup this repo, but I get the following error when running to make the chart.

![image](https://user-images.githubusercontent.com/127203685/223412769-0d7c355f-2b8f-4a13-9bbb-876441d43b83.png)

I double checked my token and created a new one but I still get the same error.

I was wondering if this might be because the organization I want to create the burndown for is a GitHub enterprise and maybe this isn't currently supported?

Thanks very much

<a href="https://polar.sh/thehale/github-projects-burndown-chart/issues/28">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/thehale/github-projects-burndown-chart/issues/28/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/thehale/github-projects-burndown-chart/issues/28/pledge.svg">
</picture>
</a>

**Comment by thehale** [comment]
@naomimow I don't have access to a GitHub enterprise account, so I'm unable to directly test this bug.

Some initial questions I would consider:
 - Are you working with Projects (Classic) or the new GitHub Projects? (We currently only support Classic projects)
 - Are you connecting to github.com or a GHES instance?
 - Are you using the traditional personal access tokens (i.e. PATs) or the new fine-grained PATs? (Fine grained PATs don't yet work with GitHub's GraphQL APIs which are used "under-the-hood" in this project).

**Comment by thehale** [comment]
*Side Note:* In the future, could you copy and paste the text of the error messages instead of using a screenshot? That makes it easier to read/debug.

Thanks!

**Comment by thehale** [comment]
Most issues with the new GitHub projects have been resolved by #31 which was released in version [v1.5.0](https://github.com/thehale/github-projects-burndown-chart/releases/tag/v1.5.0).

If issues persist with GitHub Enterprise accounts, we can re-open this issue or create a new one.
